### ISSUE TITLE
Error handling, OWTFContainer class

### ISSUE THREAD

**Issue by rasjostrom** [Kodkollektivet/owtf-valhalla#29]
As of right now errors are being handled by just raising a general exception with a message. Some proper error handling here is needed.

**Comment by jherrlin** [comment]
What do you think @rasjostrom .
Should we create custom exceptions for the class or should we use existing?

**Comment by rasjostrom** [comment]
Maybe, but more importantly we should try to recover from the errors where possible!

**Comment by jherrlin** [comment]
This was solved in #33 , good work @SpyrosMArtel !
I will close this issue now.
